name: Bump Seed Generation

on:
  workflow_dispatch:
    inputs:
      chain_id:
        description: Network chain ID to bump
        required: true
        type: string

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Fetch latest release manifest
        id: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          api_url="https://api.github.com/repos/${{ github.repository }}/releases/latest"
          response=$(curl -sSL \
            -H "authorization: Bearer $GITHUB_TOKEN" \
            -H "accept: application/vnd.github+json" \
            "$api_url")
          tag=$(jq -r '.tag_name' <<<"$response")
          if [ -z "$tag" ] || [ "$tag" = "null" ]; then
            echo "No releases found; run the remote-sync workflow first." >&2
            exit 1
          fi
          manifest_url=$(jq -r '.assets[] | select(.name == "manifest.yaml") | .browser_download_url' <<<"$response")
          if [ -z "$manifest_url" ] || [ "$manifest_url" = "null" ]; then
            echo "manifest.yaml asset not found in latest release." >&2
            exit 1
          fi
          mkdir -p artifacts
          curl -sSL \
            -H "authorization: Bearer $GITHUB_TOKEN" \
            "$manifest_url" \
            -o artifacts/manifest.yaml
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "manifest_path=artifacts/manifest.yaml" >> "$GITHUB_OUTPUT"

      - name: Bump seed generation
        id: bump
        env:
          CHAIN_ID: ${{ github.event.inputs.chain_id }}
        run: |
          set -euo pipefail

          if ! [[ "$CHAIN_ID" =~ ^[0-9]+$ ]]; then
            echo "chain_id must be a positive integer" >&2
            exit 1
          fi

          manifest_path="${{ steps.latest.outputs.manifest_path }}"
          OUTPUT=$(nix develop --command cargo run --quiet --bin bump-seed-generation -- "$CHAIN_ID" "$manifest_path")
          echo "$OUTPUT"
          PREVIOUS=$(grep '^previous=' <<< "$OUTPUT" | head -n1 | cut -d= -f2)
          NEXT=$(grep '^next=' <<< "$OUTPUT" | head -n1 | cut -d= -f2)
          echo "previous=$PREVIOUS" >> "$GITHUB_OUTPUT"
          echo "next=$NEXT" >> "$GITHUB_OUTPUT"

      - name: Upload updated manifest to release
        if: github.ref == 'refs/heads/main'
        env:
          CHAIN_ID: ${{ github.event.inputs.chain_id }}
          NEXT: ${{ steps.bump.outputs.next }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.latest.outputs.tag }}
          files: |
            ${{ steps.latest.outputs.manifest_path }}
          overwrite: true
