name: Bump Seed Generation

on:
  workflow_dispatch:
    inputs:
      chain_id:
        description: Network chain ID to bump
        required: true
        type: string

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump seed generation
        id: bump
        env:
          CHAIN_ID: ${{ github.event.inputs.chain_id }}
        run: |
          set -euo pipefail

          if ! [[ "$CHAIN_ID" =~ ^[0-9]+$ ]]; then
            echo "chain_id must be a positive integer" >&2
            exit 1
          fi

          OUTPUT=$(nix develop --command cargo run --quiet --bin bump-seed-generation -- "$CHAIN_ID")
          echo "$OUTPUT"
          PREVIOUS=$(grep '^previous=' <<< "$OUTPUT" | head -n1 | cut -d= -f2)
          NEXT=$(grep '^next=' <<< "$OUTPUT" | head -n1 | cut -d= -f2)
          echo "previous=$PREVIOUS" >> "$GITHUB_OUTPUT"
          echo "next=$NEXT" >> "$GITHUB_OUTPUT"

      - name: Show manifest diff
        run: git diff

      - name: Configure Git
        if: github.ref == 'refs/heads/main'
        env:
          CI_GIT_USER: ${{ secrets.CI_GIT_USER }}
          CI_GIT_EMAIL: ${{ secrets.CI_GIT_EMAIL }}
        run: |
          set -euo pipefail
          if [ -z "${CI_GIT_USER:-}" ] || [ -z "${CI_GIT_EMAIL:-}" ]; then
            echo "CI_GIT_USER and CI_GIT_EMAIL secrets must be set to commit." >&2
            exit 1
          fi
          git config user.name "$CI_GIT_USER"
          git config user.email "$CI_GIT_EMAIL"

      - name: Commit seed bump
        if: github.ref == 'refs/heads/main'
        env:
          CHAIN_ID: ${{ github.event.inputs.chain_id }}
          NEXT: ${{ steps.bump.outputs.next }}
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git add data/manifest.yaml
          git commit -m "bump seed generation for chain ${CHAIN_ID} to ${NEXT}"
          git push origin "${GITHUB_REF#refs/heads/}"
