name: Remote Sync

on:
  workflow_dispatch:

concurrency:
  group: remote-sync
  cancel-in-progress: false

env:
  COMMIT_HASH: ${{ vars.COMMIT_HASH }}
  HYPERRPC_API_TOKEN: ${{ secrets.HYPERRPC_API_TOKEN }}

jobs:
  run-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Determine release metadata
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            tag="sync-${GITHUB_RUN_ID}"
            echo "RELEASE_TAG=$tag" >> "$GITHUB_ENV"
            echo "RELEASE_NAME=Remote Sync $tag" >> "$GITHUB_ENV"
            echo "CREATE_RELEASE=true" >> "$GITHUB_ENV"
          else
            echo "CREATE_RELEASE=false" >> "$GITHUB_ENV"
          fi
          echo "DATA_CHANGED=false" >> "$GITHUB_ENV"
      - name: Run sync process
        run: nix develop --command cargo run --release
      - name: Configure Git
        if: github.ref == 'refs/heads/main'
        env:
          CI_GIT_USER: ${{ secrets.CI_GIT_USER }}
          CI_GIT_EMAIL: ${{ secrets.CI_GIT_EMAIL }}
        run: |
          set -euo pipefail
          if [ -z "${CI_GIT_USER:-}" ] || [ -z "${CI_GIT_EMAIL:-}" ]; then
            echo "CI_GIT_USER and CI_GIT_EMAIL secrets must be set to commit dumps." >&2
            exit 1
          fi
          git config user.name "$CI_GIT_USER"
          git config user.email "$CI_GIT_EMAIL"
      - name: Commit updated dumps
        if: github.ref == 'refs/heads/main'
        run: |
          set -euo pipefail
          CHANGES=$(git status --porcelain -- data || true)
          if [ -z "$CHANGES" ]; then
            echo "No dump changes detected; skipping commit."
            exit 0
          fi

          echo "DATA_CHANGED=true" >> "$GITHUB_ENV"

          git add data
          git commit -m "update orderbook dump"
          git push origin "${GITHUB_REF#refs/heads/}"
      - name: Publish release assets
        if: env.CREATE_RELEASE == 'true' && env.DATA_CHANGED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          target_commitish: ${{ github.sha }}
          files: |
            data/manifest.yaml
            data/*.sql.gz
