name: Remote Sync

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

concurrency:
  group: remote-sync
  cancel-in-progress: false

env:
  COMMIT_HASH: ${{ secrets.COMMIT_HASH }}
  HYPERRPC_API_TOKEN: ${{ secrets.HYPERRPC_API_TOKEN }}

jobs:
  run-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Run sync process
        run: nix develop --command cargo run --release
      - name: Configure Git
        if: github.ref == 'refs/heads/main'
        env:
          CI_GIT_USER: ${{ secrets.CI_GIT_USER }}
          CI_GIT_EMAIL: ${{ secrets.CI_GIT_EMAIL }}
        run: |
          set -euo pipefail
          if [ -z "${CI_GIT_USER:-}" ] || [ -z "${CI_GIT_EMAIL:-}" ]; then
            echo "CI_GIT_USER and CI_GIT_EMAIL secrets must be set to commit dumps." >&2
            exit 1
          fi
          git config user.name "$CI_GIT_USER"
          git config user.email "$CI_GIT_EMAIL"
      - name: Commit updated dumps
        if: github.ref == 'refs/heads/main'
        run: |
          set -euo pipefail
          CHANGES=$(git status --porcelain -- data || true)
          if [ -z "$CHANGES" ]; then
            echo "No dump changes detected; skipping commit.";
            exit 0
          fi

          git add data
          git commit -m "chore: update orderbook dump"
          git push origin "${GITHUB_REF#refs/heads/}"
